name: GraspLoss
instantiate_config:
  _target_: lift3d.loss.grasp_losses.GraspLoss
  w_heat: 1.0
  w_quat: 0.5
  w_grip: 0.1
  use_focal: false
  focal_alpha: 0.25
  focal_gamma: 2.0
  pos_weight_grip: null
